CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY,
	name VARCHAR (255) NOT NULL, 
	username VARCHAR (50) UNIQUE NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR (255) NOT NULL,
  	created_at TIMESTAMP NOT NULL, 
  	deleted_at TIMESTAMP
);